import { Ruda, Indie_Flower,Hind_Madurai } from 'next/font/google';
import "./globals.css";

const indie = Indie_Flower({
  subsets: ["latin"],
  variable: "--font-indie",
  weight: "400",
});

const ruda = Ruda({
  subsets: ["latin"],
  variable: "--font-ruda",
  weight: "400", // Choose the appropriate weight as per the Google Fonts page
});

const hindMadurai = Hind_Madurai({
  subsets: ['latin'],
  variable: '--font-hind-madurai',
  weight: '600', // Choose the appropriate weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${hindMadurai.className}`}
      >
        {children}
      </body>
    </html>
  );
}
